---
- hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        update_cache: yes

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove swap entry from fstab
      replace:
        path: /etc/fstab
        regexp: '^\s*([^#]\S*\s+)swap(\s+)'
        replace: '# \1swap\2'

