---
- hosts: all
  become: yes
  tasks:
    - name: Install containerd
      apt:
        name: containerd
        state: present
    - name: Create containerd directory
      file:
        path: /etc/containerd
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Configure containerd
      shell: |
        containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Enable systemd cgroup driver
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: yes
