---
- hosts: all
  become: yes
  tasks:
    - name: Install dependencies
    - apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present
        update_cache: yes

    - name: Add Kubernetes GPG key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key \
        | gpg --dearmor -o /usr/share/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /usr/share/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes APT repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        allow_unauthenticated: yes

- hosts: k8s_master
  become: yes
  tasks:
    - name: Initialize Kubernetes master
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init

    - name: Create kube config for user
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      environment:
        HOME: "/home/{{ ansible_user }}"

    - name: Install Flannel network
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"

    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Set join command fact
      set_fact:
        worker_join: "{{ join_command.stdout }}"

- hosts: k8s_workers
  become: yes
  vars:
    master_host: "{{ hostvars['k8s_master'].ansible_host }}"
  tasks:
    - name: Join worker nodes
      shell: "{{ hostvars['k8s_master']['worker_join'] }}"
