- hosts: worker2
  become: yes
  tasks:
    - name: Join cluster
      command: "{{ hostvars['master'].worker_join_cmd }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: hostvars['master'].worker_join_cmd is defined
